import sys
import configparser

config = configparser.ConfigParser()
config.optionxform = str

ini_file, out_file = sys.argv[1], sys.argv[2]
config.read(ini_file)

with open(out_file, "w") as f:
    # TODO(mfd) : write a header that says this is autogenerated
    for name, value in config["Counters"].items():
        flag = "1" if value.lower() == "on" else "0"
        # TODO(mfd) : consider using constexpr bool
        f.write(f"#define COUNTER_{name} {flag}\n")
